# Die "events"-Sektion ist notwendig
events {
    worker_connections 1024;  # Maximale Anzahl an Verbindungen pro Worker-Prozess
}

# Der HTTP-Block, in dem alle Server und Webspezifischen Einstellungen enthalten sind
http {
    include       mime.types;  # MIME-Typen für das Server-Setup
    default_type  application/octet-stream;
  
    # GZIP-Kompression aktivieren
    gzip on;
    gzip_types text/plain text/css application/javascript;

    # Der Server-Block für deine Vite-App
    server {
        listen 80;
        server_name _;

        root /usr/share/nginx/html;  # Der Pfad zu den statischen Dateien
        index index.html;  # Standard-Indexdatei

        # Konfiguration, die versucht, eine Datei zu finden, und wenn nicht, auf index.html weiterleitet
        location / {
            try_files $uri $uri/ /index.html;
        }

        # Optional: Eine Fehlerseite für 404
        error_page 404 /404.html;
        location = /404.html {
            root /usr/share/nginx/html;
        }
    }
}
